### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by zoltankis** [zoltankis/SEBC#13]
Start Kerberize cluster

**Comment by mfernest** [comment]
See commit [7aa5101](https://github.com/zoltankis/SEBC/commit/7aa5101f2543580795540d4ee2c49c65ddaf3c53)

**Comment by mfernest** [comment]
See commit [ca977f2](https://github.com/zoltankis/SEBC/commit/ca977f2197ab8329e835da7f5e1829c382f310b9)
