### ISSUE TITLE
Configure Sentry

### ISSUE THREAD

**Issue by zoltankis** [zoltankis/SEBC#14]
Hi Ernest and Siwicki,
 today I checked my challange that I completed yesterday and I note that in the exam nerves and big hurry in the end I forgot to create the issue for the last sentry exercise so I created it now.
 I really hope its acceptable because as you can see the result file (challenges/labs/6_results.md) were uploaded during the exam.
 
 Many thanks for the whole week and Best Regards,
 Zoltan

**Comment by rsiwicki** [comment]
Thanks Zoltán. It was an awesome week and a fantastic class. Note that it is a really tough week. To make it to the starting line on Friday is a victory in itself.

**Comment by mfernest** [comment]
See commit [36271c3](https://github.com/zoltankis/SEBC/commit/36271c3b5d9e169df11bd94caf10827c031a6ad7)
